{% set name = "alice" %}
{% set version = "1.3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/analogdevicesinc/alice/archive/package-v1.3.zip
        #url: https://github.com/analogdevicesinc/{{ name }}/archive/v{{ version }}.tar.gz
        #sha256: 3017d19ae3fb654b7a698461f6efe4972df7ddc7b735e983b79e2a178055dca7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - tk
    - libsmu
    - numpy
    - python >=3.6

test:
  imports:
    - alice

about:
  home: https://wiki.analog.com/university/tools/m1k/alice/desk-top-users-guide
  summary: Active Learning Interface (for) Circuits (and) Electronics:
  license: LicenseRef-BSD-Analog-Devices
  license_family: BSD
  license_file: LICENSE_ADIBSD
  description: |
    The ALICE Desktop software interface is a collection of software instruments
    written for use with the active learning hardware modules ADALM1000 (M1K) and
    ADALM2000 (M2K).
  doc_url: https://wiki.analog.com/university/tools/m1k/alice/desk-top-users-guide
  dev_url: https://github.com/analogdevicesinc/alice

extra:
  recipe-maintainers:
    - tfcollins
