{% set name = "libm2k" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/analogdevicesinc/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 3ffa9e7bb2ab9d2b6af9075b60bc0fb3e7d73616d5d4851f910861ebc4724908

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libm2k', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - {{ cdt('libudev-devel') }}  # [linux]
    - make  # [not win]
    - ninja  # [win]
    - libiio
    - swig
  host:
    - libiio
    - libusb >=1
    - python
  run:
    - python

test:
  commands:
    # verify that headers get installed
    - test -f $PREFIX/include/libm2k/m2k.hpp  # [not win]
    - if not exist %PREFIX%\\Library\\include\\libm2k\\m2k.hpp exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/libm2k${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\libm2k.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\libm2k.lib exit 1  # [win]
  imports:
    - libm2k
about:
  home: https://github.com/analogdevicesinc/libsmu
  license: MIT
  license_family: BSD
  license_file: LICENSE
  summary: 'Software abstractions for the analog signal exploration tools'
  description: |
    libsmu contains abstractions for streaming data to and from USB-connected
    analog interface devices, currently supporting the Analog Devices' ADALM1000.
    Building off of LibUSB for cross-platform operation, it offers the sourcing
    of repeated waveforms, configuration of hardware, and measuring of signals.
  doc_url: https://analogdevicesinc.github.io/libsmu/
  dev_url: https://github.com/analogdevicesinc/libsmu

extra:
  recipe-maintainers:
    - tfcollins
